version: "3.2"

services:
  db:
    image: postgres:14
    container_name: wishlify-db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: wishlify-app
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - db
